services:
  file-explorer-backend:
    build: ./backend
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - MOCK_ROOT=/app/sandbox
    volumes:
      - ./tests/sandbox/mock_root:/app/sandbox

  file-explorer-frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - file-explorer-backend
