services:
  explorer-backend:
    build: ./backend
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    environment:
      - PORT=${PORT:-5000}
      - MOCK_ROOT=/app/sandbox
    volumes:
      - ./tests/sandbox/mock_root:/app/sandbox

  explorer-frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - explorer-backend
